/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.BorderLayout;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Mayur
 */
public class Home extends javax.swing.JFrame {
GridBagLayout layout =new GridBagLayout();
    Panel1 p1;
    Panel2 p2;
    Panel3 p3;
    Panel4 p4;
    Panel5 p5;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        p1=new Panel1();
        p2=new Panel2();
        p3=new Panel3();
        p4=new Panel4();
        p5=new Panel5();
        
        DyanamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DyanamicPanel.add(p1,c);
        
        c.gridx=0;
        c.gridy=0;
        DyanamicPanel.add(p2,c);
        c.gridx=0;
        c.gridy=0;
        DyanamicPanel.add(p3,c);
        c.gridx=0;
        c.gridy=0;
        DyanamicPanel.add(p4,c);
        c.gridx=0;
        c.gridy=0;
        DyanamicPanel.add(p5,c);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        label1.setBackground(Color.white);
        label1.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PannelButton = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        DyanamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PannelButton.setBackground(new java.awt.Color(0, 0, 102));
        PannelButton.setForeground(new java.awt.Color(255, 255, 255));
        PannelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PannelButtonMouseClicked(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("General");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("System App");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Web App");
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
        });

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("System App Restore");
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4MouseClicked(evt);
            }
        });

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Web App Restore");
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PannelButtonLayout = new javax.swing.GroupLayout(PannelButton);
        PannelButton.setLayout(PannelButtonLayout);
        PannelButtonLayout.setHorizontalGroup(
            PannelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelButtonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(PannelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        PannelButtonLayout.setVerticalGroup(
            PannelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelButtonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout DyanamicPanelLayout = new javax.swing.GroupLayout(DyanamicPanel);
        DyanamicPanel.setLayout(DyanamicPanelLayout);
        DyanamicPanelLayout.setHorizontalGroup(
            DyanamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        DyanamicPanelLayout.setVerticalGroup(
            DyanamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PannelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DyanamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DyanamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PannelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PannelButtonMouseClicked
             // TODO add your handling code here:
    }//GEN-LAST:event_PannelButtonMouseClicked

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        label1.setBackground(Color.white);
        label1.setForeground(Color.black);
        
        label2.setBackground(PannelButton.getBackground());
        label3.setBackground(PannelButton.getBackground());
        label4.setBackground(PannelButton.getBackground());
        label5.setBackground(PannelButton.getBackground());
        
        label2.setForeground(Color.white); 
        label3.setForeground(Color.white); 
        label4.setForeground(Color.white); 
        label5.setForeground(Color.white); 
        
        
         p2.setVisible(false);
         p3.setVisible(false);
         p4.setVisible(false);
         p5.setVisible(false);
         p1.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_label1MouseClicked

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        label1.setBackground(PannelButton.getBackground());
        label3.setBackground(PannelButton.getBackground());
        label4.setBackground(PannelButton.getBackground());
        label5.setBackground(PannelButton.getBackground());
         
        label1.setForeground(Color.white); 
        label3.setForeground(Color.white); 
        label4.setForeground(Color.white); 
       
        label5.setForeground(Color.white); 
        
        
        label2.setBackground(Color.white);
        label2.setForeground(Color.black); 
         p2.setVisible(true);
         p3.setVisible(false);
         p4.setVisible(false);
         p5.setVisible(false);
         p1.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_label2MouseClicked

    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
         label3.setBackground(Color.white);
         label3.setForeground(Color.black); 
        
         
        label2.setBackground(PannelButton.getBackground());
        label1.setBackground(PannelButton.getBackground());
        label4.setBackground(PannelButton.getBackground());
        label5.setBackground(PannelButton.getBackground());
        
        label2.setForeground(Color.white); 
        label1.setForeground(Color.white); 
        label4.setForeground(Color.white); 
        label5.setForeground(Color.white); 
        
        
         
        p2.setVisible(false);
         p3.setVisible(true);
         p4.setVisible(false);
         p5.setVisible(false);
         p1.setVisible(false); 

        // TODO add your handling code here:
    }//GEN-LAST:event_label3MouseClicked

    private void label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseClicked
         label4.setBackground(Color.white);
         label4.setForeground(Color.black); 
       
         
        label2.setBackground(PannelButton.getBackground());
        label3.setBackground(PannelButton.getBackground());
        label1.setBackground(PannelButton.getBackground());
        label5.setBackground(PannelButton.getBackground());
        
        label2.setForeground(Color.white); 
        label3.setForeground(Color.white); 
        label1.setForeground(Color.white); 
        label5.setForeground(Color.white); 
        
        
         
           p2.setVisible(false);
         p3.setVisible(false);
         p4.setVisible(true);
         p5.setVisible(false);
         p1.setVisible(false); 


        // TODO add your handling code here:
    }//GEN-LAST:event_label4MouseClicked

    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
        label5.setBackground(Color.white);
        label5.setForeground(Color.black); 
       
        
        label2.setBackground(PannelButton.getBackground());
        label3.setBackground(PannelButton.getBackground());
        label4.setBackground(PannelButton.getBackground());
        label1.setBackground(PannelButton.getBackground());
        
        label2.setForeground(Color.white); 
        label3.setForeground(Color.white); 
        label4.setForeground(Color.white); 
        label1.setForeground(Color.white); 
        
        
        
         p2.setVisible(false);
         p3.setVisible(false);
         p4.setVisible(false);
         p5.setVisible(true);
         p1.setVisible(false);           

// TODO add your handling code here:
    }//GEN-LAST:event_label5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DyanamicPanel;
    private javax.swing.JPanel PannelButton;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
