/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mayur
 */
public class Panel3 extends javax.swing.JPanel  {
    static int flag = 0;
    /**
     * Creates new form Panel3
     */
    //Panel3 pp=new Panel3();
    
    public Panel3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();

        start.setText("START");
        start.setBackground(Color.GREEN);
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        if(flag == 1){
            stop();
            start.setBackground(Color.GREEN);
            start.setText("START");
            flag = 0;
            
        }
        else{
            try {
                FileWriter fw=null;
                start.setBackground(Color.RED);
                start.setText("STOP");
                flag = 1;
                fw = new FileWriter("flags2");
                fw.write("1");
                fw.close();
                ///pp.start();
                Thread t=new Thread(){
                    @Override
                    public void run(){
                        try {
                            webdump.main(new String [0]);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Panel3.class.getName()).log(Level.SEVERE, null, ex);
                        }
                      }
                };
                t.start();        
            } catch (IOException ex) {
                Logger.getLogger(Panel3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_startActionPerformed

    public static void stop(){
        FileWriter fw=null;
        try {
            fw = new FileWriter("flags2");
            fw.write("0");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Panel2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables

  
    
}
